# Generated by Django 4.2.19 on 2025-03-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwoAQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=100)),
                ('source_file', models.FileField(upload_to='')),
                ('question', models.TextField()),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField()),
                ('option4', models.TextField()),
                ('option5', models.TextField()),
                ('answer_index', models.TextField()),
                ('explanation', models.TextField()),
                ('explanation_other1', models.TextField()),
                ('explanation_other2', models.TextField()),
                ('explanation_other3', models.TextField()),
                ('explanation_other4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='upload_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
