# Generated by Django 4.2.19 on 2025-03-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoaquestions',
            name='task_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='twoaquestions',
            name='answer_index',
            field=models.IntegerField(),
        ),
    ]
