# Generated by Django 4.2.19 on 2025-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_twoaquestions_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoaquestions',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
